frequency: 20
sensor_timeout: 0.150
two_d_mode: true

map_frame: map
odom_frame: odom            
base_link_frame: duckiebot4/footprint
world_frame: odom

twist0: /duckiebot4/forward_kinematics_node/duckiebot_base/twist
twist0_config: [false, false, false,
                false, false, false,
                true, true, false,
                false, false, true,
                false, false, false]