# footprint: [[-0.11, -0.065], [-0.11, 0.065], [0.11, 0.065], [0.11, -0.065]]
robot_radius: 0.08
footprint_padding: 0.0

robot_base_frame: duckiebot4/footprint
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.55

resolution: 0.05

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

inflation:
    inflation_radius: 0.1

inflation_local:
    inflation_radius: 0.01
