controller_frequency: 5.0
recovery_behavior_enabled: false
clearing_rotation_allowed: false

GlobalPlanner:
  allow_unknown: true # Specifies whether or not to allow navfn to create plans that traverse unknown space.
  default_tolerance: 0.02 # A tolerance on the goal point for the planner.
  use_dijkstra: true # if false it uses A*
  use_quadratic: true
  use_grid_path: false
  old_navfn_behaviour: true # imitate navfn behaviour
  outline_map: true

TebLocalPlannerROS:

  # Robot
  acc_lim_x: 2
  acc_lim_theta: 13
  max_vel_x: 0.2
  max_vel_theta: 8.3
  max_vel_x_backwards: 0.2
  min_turning_radius: 0.05
  max_vel_y: 0.0
  footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
    type: "circular"
    radius: 0.08
    # vertices: [[-0.11, -0.065], [-0.11, 0.065], [0.11, 0.065], [0.11, -0.065]] # for type "polygon"

  # GoalTolerance
    
  xy_goal_tolerance: 0.08
  yaw_goal_tolerance: 0.1
  free_goal_vel: false

  # Trajectory

  max_global_plan_lookahead_dist: 0.35
  publish_feedback: false # disable when debugging is finished
  shrink_horizon_backup: true
  shrink_horizon_min_duration: 5
    
  # Obstacles
    
  min_obstacle_dist: 0.02
  include_costmap_obstacles: false
  costmap_obstacles_behind_robot_dist: 0.3

  # Optimization

  penalty_epsilon: 0.1
  weight_kinematics_forward_drive: 1000

  # Homotopy Class Planner

  enable_homotopy_class_planning: true
  enable_multithreading: true
  max_number_classes: 2
  roadmap_graph_area_width: 1

  # Miscellaneous Parameters

  odom_topic: odom
  map_frame: map